name: Deploy Audit Processors
env:
  DEPLOYER_ROLE: arn:aws:iam::761723964695:role/plat-872-audit-pipeline-GitHubActionsRole-6FVSYM2IO5VO

on:
  push:
    branches:
      - PLAT-1092
#     paths:
#       - "audit-processors"
#   workflow_run:
#     workflows: ["Build modules"]
#     types:
#       - completed

# on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.DEPLOYER_ROLE }}
          aws-region: eu-west-2

      - name: Get Signing Profile
        run: |
          SIGNING_ARN=`aws signer get-signing-profile \
          --profile-name di_auth_lambda_signing_20220215170204371800000001`
          echo $SIGNING_ARN
          echo "SIGNING_ARN=$SIGNING_ARN" >> $GITHUB_ENV